baseURL = "http://example.org/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Isaac Dolphin :: Software Development Student"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Â© Isaac Dolphin 2021, all rights reserved."
footerLogo = "images/site-navigation/logo-white.png"
formspreeURL = "https://formspree.io/f/xknkwoop"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "2 Meredith Way, Gloucester, GL4 0UD, UK."
email = "isaacdolphin555@gmail.com"
openingHours = "10am - 11pm (reply time depends on avaliability)"
phone = "+44 7934 235536"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/isaac-dolphin-651057190/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
